#!/usr/bin/env perl

use utf8;
use POSIX;
use strict;
use warnings;

my $state; # down or up
my $message;
my $connected; # connected or disconnected
my $ip_address;
my $device_name;

# remove whitespaces
sub trim {
	my $s = shift;
	$s =~ s/^\s+|\s+$//g;
	return $s;
};

$device_name = `ip addr | egrep '^[0-9]: e' | awk '{print \$2}'`;
$device_name = substr(trim($device_name), 0, -1);

$state = `ip addr show $device_name | grep ',UP'`;

if ($state eq "") {
	$message = " down\n";
	printf "$message\n";
	print "#E53935\n";
} else {
	$connected = `ip addr show $device_name | grep 'state UP'`;

	if ($connected eq "") {
		$message = " up\n";
		printf "$message\n";
	} else {
		$ip_address = `ip addr show $device_name | egrep 'inet ' | awk '{print \$2}' | tr '/' ' ' | awk '{print \$1}'`;
		$ip_address = trim($ip_address);

		if ($ip_address eq "") {
			$message = " connecting\n";
			printf "$message\n";
			print "#00BFFF\n";
		} else {
			$message = " on $ip_address\n";
			printf "$message\n";
			print "#00BFFF\n";
		}
	}
}
