#!/usr/bin/env perl

use utf8;
use POSIX;
use strict;
use warnings;

my $used;
my $total;
my $ram_used;
my $ram_total;
my $swap_used;
my $swap_total;

$ram_used = `free | grep Mem | awk '{print \$3}'`;
$ram_total = `free | grep Mem | awk '{print \$2}'`;

$swap_used=`free | grep Swap | awk '{print \$3}'`;
$swap_total=`free | grep Swap | awk '{print \$2}'`;

$total = ($ram_total + $swap_total) / 1024.0 / 1024.0;
$used = ($ram_used + $swap_used) / 1024.0 / 1024.0;

printf "%.1fG \/ %.1fG", $used, $total;
