#!/usr/bin/env perl

my $master;

# remove whitespaces
sub trim {
	my $s = shift;
	$s =~ s/^\s+|\s+$//g;
	return $s;
};

$master = `amixer sget Master | egrep "Mono:" | awk '{print \$6}'`;
$master = substr(trim($master), 1, -1);

$headphone = `amixer sget Headphone | egrep "Front Left:" | awk '{print \$7}'`;
$headphone = substr(trim($headphone), 1, -1);

if ($headphone eq "off" or $master eq "off") {
  `amixer -q sset Headphone on`;
  `amixer -q sset Master on`;

} else {
  `amixer -q sset Headphone off`;
  `amixer -q sset Master off`;
}
