#!/usr/bin/env perl

use utf8;
use strict;
use warnings;

my $muted;
my $volume;

# remove whitespaces
sub trim {
	my $s = shift;
	$s =~ s/^\s+|\s+$//g;
	return $s;
};

$volume = `amixer | egrep ^"  Front Left: Playback" | awk '{print \$5}'`;
if ($volume eq "") {
	$volume = `amixer | egrep ^"  Mono: Playback" | awk '{print \$4}'`;
}
$volume = substr(trim($volume), 1, -2);
$volume = $volume + 0;

$muted = `amixer | egrep ^"  Front Left: Playback" | awk '{print \$6}'`;

if ($muted eq "") {
	$muted = `amixer | egrep ^"  Mono: Playback" | awk '{print \$5}'`;
}

$muted = substr(trim($muted), 1, -1);

if ($muted eq "off") {
	$volume = " $volume\n";
	printf "$volume\n";
	# print "#FF0000\n";
	print "#E53935\n";
} elsif ($volume == 0) {
	printf " $volume\n";
} elsif ($volume < 40) {
	printf " $volume\n";
} else {
	printf " $volume\n";
}
