#!/bin/sh

PROC="$(ps -ef | grep "i3lock" | grep -v "grep" | wc -l)"

if [ "$PROC" -eq 0 ];then
	scrot -z /tmp/screenshot.png
	convert /tmp/screenshot.png -blur 0x5 /tmp/screenshotblur.png
	i3lock -i /tmp/screenshotblur.png
	rm /tmp/screenshot*.png
fi
